# Generated by Django 3.0.6 on 2020-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='ingredients')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='recipes')),
                ('description', models.TextField(blank=True)),
                ('method', models.TextField(blank=True)),
                ('ingredients', models.ManyToManyField(blank=True, to='recipes.Ingredient')),
            ],
            options={
                'verbose_name_plural': 'recipes',
                'ordering': ['name'],
            },
        ),
    ]
