# Generated by Django 3.0.6 on 2020-05-20 11:55

import random
import mimesis

from django.db import migrations


mimesis_food = mimesis.Food()
mimesis_text = mimesis.Text()
mimesis_internet = mimesis.Internet()


def ingredient_name():
    name = ''
    category = random.choice(['food', 'vegetable', 'spices'])
    if category == 'food':
        name = mimesis_food.fruit()
    elif category == 'vegetable':
        name = mimesis_food.vegetable()
    elif category == 'spices':
        name = mimesis_food.spices()
    return name


def get_random_ingredients(apps, n=10):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    ingredients = list(Ingredient.objects.all())

    return random.sample(ingredients, random.randint(2, n))


def populate_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    for _ in range(30):
        Ingredient.objects.get_or_create(
            name=ingredient_name()
        )


def populate_recipes(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    for _ in range(10):
        recipe, created = Recipe.objects.get_or_create(
            name=mimesis_food.dish(),
            description=mimesis_text.text(1),
        )
        ingredients = get_random_ingredients(apps)
        recipe.ingredients.set(ingredients)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_ingredients),
        migrations.RunPython(populate_recipes),
    ]
